import { createEnrollment, createInvitation, createOrganizerEncryptionKey, createResponse, verifyInvitation } from './participant-exchange.js';
const $=(id)=>document.querySelector('#'+id); let enrollment, invitation, reviewedInvitationValue;
const setMessage=(id,text,error=false)=>{$(id).textContent=text;$(id).classList.toggle('error',error);};
async function copy(value,messageId){try{await navigator.clipboard.writeText(value);setMessage(messageId,'Copied to clipboard.');}catch{setMessage(messageId,'Copy was blocked. Select the packet and copy it manually.',true);}}
$('enroll').onclick=()=>{try{enrollment=createEnrollment($('slot').value);localStorage.setItem(`veilconsent:${$('slot').value}:secrets`,JSON.stringify({approvalSecret:enrollment.secret,revocationSecret:enrollment.revocationSecret}));$('enrollment').value=enrollment.packet;$('copyEnrollment').disabled=false;$('enrollmentDetails').open=true;$('progress1').classList.add('done');$('progress2').classList.add('active');setMessage('enrollMessage','Credential ready. Copy the enrollment packet to the organizer, then wait for a signed invitation.');}catch(error){setMessage('enrollMessage',error.message,true);}};
$('copyEnrollment').onclick=()=>copy($('enrollment').value,'enrollMessage');
async function reviewInvitation(){try{reviewedInvitationValue=$('invitation').value.trim();invitation=await verifyInvitation(reviewedInvitationValue,$('organizerFingerprintInput').value);const purpose=invitation.purpose;$('reviewSlot').textContent=invitation.slot;$('reviewTask').textContent=purpose.task;$('reviewModel').textContent=purpose.model;$('reviewRecipients').textContent=purpose.recipients;$('reviewRetention').textContent=purpose.retention;$('reviewExpiry').textContent=new Date(Number(invitation.expiry)*1000).toLocaleString();$('reviewRequest').textContent=invitation.request.slice(0,16)+'…'+invitation.request.slice(-8);$('reviewOrganizer').textContent=invitation.organizerFingerprint.match(/.{1,8}/g).join(' ');$('reviewCard').style.display='block';$('progress2').classList.add('done');$('progress3').classList.add('active');setMessage('reviewMessage',$('organizerFingerprintInput').value?'Signature and trusted organizer fingerprint verified. Review every purpose field before answering.':'Signature verified. Compare the organizer fingerprint through a separate trusted channel before answering.');}catch(error){$('reviewCard').style.display='none';setMessage('reviewMessage',error.message,true);}}
$('review').onclick=reviewInvitation;
async function answer(approved){try{if(!invitation)throw new Error('Review an invitation first');if($('invitation').value.trim()!==reviewedInvitationValue)throw new Error('Invitation changed after review. Verify it again before answering.');const storageKey=`veilconsent:${invitation.slot}:secrets`;const stored=JSON.parse(localStorage.getItem(storageKey)||'null');if(!stored?.approvalSecret)throw new Error(`No local credential is available for participant ${invitation.slot}`);$('response').value=await createResponse(reviewedInvitationValue,stored.approvalSecret,approved,invitation.organizerFingerprint);localStorage.setItem(storageKey,JSON.stringify({revocationSecret:stored.revocationSecret}));$('copyResponse').disabled=false;$('responseDetails').open=true;$('progress3').classList.add('done');setMessage('responseMessage',approved?'Approval encrypted. Its one-time witness was removed; your separate withdrawal key remains on this device.':'Decline encrypted. No approval witness was released; your withdrawal key remains on this device.');}catch(error){setMessage('responseMessage',error.message,true);}}
$('approve').onclick=()=>answer(true);$('decline').onclick=()=>answer(false);$('copyResponse').onclick=()=>copy($('response').value,'responseMessage');
$('clearLocal').onclick=()=>{for(const key of Object.keys(localStorage))if(key.startsWith('veilconsent:'))localStorage.removeItem(key);enrollment=undefined;invitation=undefined;reviewedInvitationValue=undefined;$('enrollment').value='';$('invitation').value='';$('response').value='';$('reviewCard').style.display='none';$('copyEnrollment').disabled=true;$('copyResponse').disabled=true;for(let i=1;i<=3;i++){$('progress'+i).classList.remove('done','active');}$('progress1').classList.add('active');setMessage('enrollMessage','Local VeilConsent credentials and response state cleared.');};

if(new URLSearchParams(location.search).get('demo')==='review'){
  enrollment=createEnrollment('B');
  $('slot').value='B';
  $('enrollment').value=enrollment.packet;
  $('copyEnrollment').disabled=false;
  $('enrollmentDetails').open=true;
  const organizer=await createOrganizerEncryptionKey();
  $('invitation').value=await createInvitation({slot:'B',credential:enrollment.credential,request:'7b'.repeat(32),purpose:{version:1,task:'Summarize decisions and action items',model:'veil-demo-v1',recipients:'Project Aurora members',retention:'24 hours',retentionSeconds:86400},expiry:Math.floor(Date.now()/1000)+3600,organizerPublicKey:organizer.publicKey,organizerSigningPublicKey:organizer.signingPublicKey,organizerSigningPrivateKey:organizer.signingKeyPair.privateKey});
  $('organizerFingerprintInput').value=organizer.signingFingerprint;
  await reviewInvitation();
  document.querySelector('.panel').style.display='none';
}
